Keley\ProductBundle\Entity\Product:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        weight:
            type: string
            length: 255
        price:
            type: integer
        image:
            type: string
            length: 255

    manyToOne:
        category:
            targetEntity: Keley\categoryBundle\Entity\Category
            inversedBy: products
            joinColumn:
                name: category_id
                referencedColumnName: id
    lifecycleCallbacks: 
        prePersist: [preUpload]
        preUpdate: [preUpload]
        postPersist: [upload]
        postUpdate: [upload]
        postRemove: [removeUpload]
